### ISSUE TITLE
metadata - filename ?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/datatester#21]
I dont think we output the actual filename in the metadata - it's part of the download URL - eg:

http://abcharitabletrust.org.uk/data/abct-data-february-2018.xlsx

It could be worth us outputting the filename specifically - esp as these will be at the end of various URL patterns, making it difficult for some to gather

**Comment by robredpath** [comment]
I'm not sure if anyone currently does this, but the file name at the end of the URL isn't necessarily the name of the file that gets downloaded to your computer. For example - GrantNav's http://grantnav.threesixtygiving.org/api/grants.json will download a file named with the format grants-TIMESTAMP.json 

What would be the use case for knowing the filename, @stevieflow ?

**Comment by stevieflow** [comment]
I think the use case would be something like:

As a data user I want to check that the Titles and Filenames of datasets, in case there is any extra information I can use.

It's a flimsy case, I agree - example could be:

- Title: "Grants made by the foundation"
- Filename "ProgrammeX_grants.xlsx

@drkane might have ideas

**Comment by robredpath** [comment]
@stevieflow - I'm not sure that's something we want to encourage! Anything useful should be in the metadata - especially as the filename is lost if someone converts the data.

**Comment by drkane** [comment]
I'd agree - doesn't seem helpful to put the filename in the metadata when it could so easily change.

**Comment by stevieflow** [comment]
OK no problem - we can forget this!

@KDuerden and I spoke about how filename *might* be useful, in terms of any potential information that could be gleaned.  As with https://github.com/ThreeSixtyGiving/registry/issues/27 I guess our first tactic could be to look at some guidance in terms of naming conventions, anyway.
