### ISSUE TITLE
Datagetter doesn't check if JSON is actually JSON before trying to manipulate it  

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datatester#41]
See #38 

Travis was failing because ValidationError isn't the only error that we can encounter here - https://github.com/ThreeSixtyGiving/datagetter/blob/master/get.py#L173 

If the file that's downloaded has a .json extension but isn't actually JSON (in this case, it was an HTML 404 page), validate() throws a JSONDecodeError which goes uncaught. 

I tried to catch both JSONDecodeError and its superclass ValueError but it didn't work as I expected. The offending file has now been removed from the registry, so logging the issue here.

**Comment by michaelwood** [comment]
Fixed in:
https://github.com/ThreeSixtyGiving/datagetter/issues/5
https://github.com/ThreeSixtyGiving/datagetter/commit/1dffbc9b1930335a0a6b6b13e3b7daa60909543f
