### ISSUE TITLE
PSA - Repo name change datagetter->datatester

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/datatester#44]
In order not to create conflicting dependencies on the datastore which will use the datagetter the getter part and the quality parts are now in separate repos. datatester and datagetter.

**For continuity of service this repo is just a rename of the datagetter so can be considered unchanged**. When the datagetter is ready as a separate project this project will depend on it and the datagetter parts will be removed. See issue #45

**Comment by robredpath** [comment]
I'm not sure that `dataquality` is the best name for this, as there's already a Data Quality Tool in the 360Giving world. I thought we'd said that we were separating out the 'daily data test' components from the 'datagetter' components? `daily-data-test` then feels like an appropriate name to use.

**Comment by michaelwood** [comment]
I went with `dataquality` because of the presence of  checks/validation (via cove) and various reports being generated by this collection of scripts. I wasn't sure if the tests are always going to be 'daily'  so didn't include that. I'm not wedded to this name though! happy for more experienced folk to determine a better name.

**Comment by robredpath** [comment]
Good point. Maybe `datatester` to go alongside `datagetter`? Although, the 'daily data test' is a well-established part of the 360Giving data infrastructure, so it is likely to be daily for a long time. More frequent doesn't make sense (the standard has daily granularity baked in), and less frequent is less useful.

**Comment by michaelwood** [comment]
Sure - Updated to `datatester`
