### ISSUE TITLE
gist report csv upload failing

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/datatester#48]
https://travis-ci.org/ThreeSixtyGiving/datatester/builds/584098703#L384 

It appears to be failing to upload the report csv, I wonder if the arguments have changed to `gist`, https://github.com/defunkt/gist shows "gist -u <id> <file>"  rather than specifying a full url path as we currently do https://github.com/ThreeSixtyGiving/datatester/blob/master/gist.sh

**Comment by michaelwood** [comment]
Travis and the datastore now working correctly again https://travis-ci.com/ThreeSixtyGiving/datatester/builds

**Comment by michaelwood** [comment]
Seems to be still causing Travis to fail, but the upload/deploy isn't actually failing (https://gist.github.com/360bot/30d835ae16e2a30efde8a63acf03628d ) . Can't recreate this outside of Travis frustratingly.

**Comment by robredpath** [comment]
@michaelwood - i've only looked at it briefly, but could this be another incarnation of Travis being blocked by an external service (Lankelly?). Their host isn't 20i (who blocked our Hetzner box), but someone else.

**Comment by michaelwood** [comment]
Turns out to be a travis-ci.org vs travis-ci.com issue. This is all working as expected now.  https://travis-ci.com/ThreeSixtyGiving/datatester
